### ISSUE TITLE
Package requirements for usage

### ISSUE THREAD

**Issue by Martin36** [Raldir/FEVEROUS#1]
I couldn't find the required packages for running the code in the example. Therefore I created a summary of them to help others. 

The following are the packages that I needed to install in order to run the example in the README file: 

```
regex
numpy
scipy
sklearn
jsonlines
tqdm
```

**Comment by Raldir** [comment]
Thank you @Martin36! We have added a requirements.txt now. More features/examples for reading in FEVEROUS data will be added in the coming days.
