### ISSUE TITLE
Module "BM25_doc_ranker" not in found

### ISSUE THREAD

**Issue by Martin36** [Raldir/FEVEROUS#11]
When I run the command: `PYTHONPATH=src python src/baseline/retriever/build_db.py --db_path data/feverous_wikiv1.db --save_path data/feverous-wiki-docs.db`, I get the following error:

```
Traceback (most recent call last):
  File "src/baseline/retriever/build_db.py", line 19, in <module>
    from baseline.drqa.retriever import utils
  File "/home/martin/FEVEROUS/src/baseline/drqa/retriever/__init__.py", line 24, in <module>
    from .BM25_doc_ranker import BM25DocRanker
ModuleNotFoundError: No module named 'baseline.drqa.retriever.BM25_doc_ranker'
```

It seems that it is looking for the module `BM25_doc_ranker`, but this module does not seem to exist in the repo.

**Comment by Raldir** [comment]
Hi Martin, thanks! A dependency issue resulting from last commit. Fixed now.
