### ISSUE TITLE
a wrong sample in the dev dataset?

### ISSUE THREAD

**Issue by leezythu** [Raldir/FEVEROUS#12]
The claim of the seventh sample in dev set is "Per Axel Rydberg, born on July 6, 1860, in Odh, Västergötland, situated outside Sweden, was a graduate of University of Nebraska–Lincoln in the field of Botany (the science of plant life and a branch of biology).". I think this sample should be refused because Västergötland is in Sweden rather than outside Sweden. However, it is labeled "SUPPORTS". 
Does anyone have any ideas?

**Comment by Raldir** [comment]
Thank you for this observation. Appears to be a labelling error! Will look into this.
