### ISSUE TITLE
sqlite3.OperationalError: no such table: wiki

### ISSUE THREAD

**Issue by lyy1994** [Raldir/FEVEROUS#23]
When I run the command 
`PYTHONPATH=src/feverous python src/feverous/baseline/retriever/build_db.py --db_path data/feverous_wikiv1.db --save_path data/feverous-wiki-docs.db` in README to reproduce the baseline, I encounter the following error message:

```
Since the GPL-licensed package `unidecode` is not installed, using Python's `unicodedata` package which yields worse results.
[INFO] 2022-02-21 20:06:52,952 - DrQA BuildDB - Reading into database...
Traceback (most recent call last):
  File "src/feverous/baseline/retriever/build_db.py", line 147, in <module>
    store_contents(
  File "src/feverous/baseline/retriever/build_db.py", line 102, in store_contents
    docs = db.get_doc_ids()
  File "/path/to/FEVEROUS/src/feverous/database/feverous_db.py", line 41, in get_doc_ids
    cursor.execute("SELECT id FROM wiki")
sqlite3.OperationalError: no such table: wiki
```

It seems that the data I downloaded is not complete. But the data is downloaded via `./scripts/download_data.sh`, which should be OK.

Thanks for helping me!

**Comment by lyy1994** [comment]
Oh, I find the reason: `unzip` was interrupted, so the database is not complete. After I unzip the file again, this error disappears.

Another small question: I find `build_db.py` takes much time, so I interrupt it and run it again in the backend. Meanwhile, I delete all newly generated files like `feverous-wiki-docs.db` and `feverous-wiki-docs.db-journal`. Is that OK?

**Comment by Raldir** [comment]
Hi @lyy1994, `build_db.py` does not modify `feverous_wikiv1.db` so running `build_db.py` again is fine after removing the generated files (the program will stop if it finds a file with the same name). Does that answer your question?

**Comment by lyy1994** [comment]
Thank you for your reply! It solves my question :)
