### ISSUE TITLE
fail to submit the predition

### ISSUE THREAD

**Issue by Jason98Xu** [Raldir/FEVEROUS#24]
Hi,
I have produced a prediction file and just wanted to obtain a result on the official evaluation website but found that did not work.
Could you please point out any mistake in the submission format? Or is it just a BUG of this platform? The screenshot of my submission is shown below that it is always reminded that 'a valid publication URL is needed', where I am quite confused about.  
<img width="600" alt="image" src="https://user-images.githubusercontent.com/34050344/167619074-5293b3e2-caf0-4408-b92b-8377d36214aa.png">

Looking forward to your prompt reply.

**Comment by Raldir** [comment]
Hi Jason, seems like a bug caused by an EvalAI update. It should work again now!

**Comment by Jason98Xu** [comment]
I saw that! Thanks a lot!
