### ISSUE TITLE
RoBERTa+NLI model in Table 4

### ISSUE THREAD

**Issue by ginaaunchat** [Raldir/FEVEROUS#25]
Is it possible to provide the RoBERTa+NLI model as described in Table 4 of the paper? 
We'd like to compare with other methods other than NEI Sampling.

**Comment by Raldir** [comment]
Hi Gina, the model we used is available as a Huggingface model:
```
model = RobertaForSequenceClassification.from_pretrained('ynie/roberta-large-snli_mnli_fever_anli_R1_R2_R3-nli', num_labels =3, return_dict=True)
```

**Comment by ginaaunchat** [comment]
Is the performance of  the RoBERTa+NLI model described in Table 4 fine-tuned?

**Comment by Raldir** [comment]
Yes.
