### ISSUE TITLE
Seeking help regarding extracting evidence content text

### ISSUE THREAD

**Issue by sayef** [Raldir/FEVEROUS#27]
Hi,

thank you for this awesome repo and dataset.

I was trying to find an example code for retrieving evidence contexts (element ids) to  their corresponding texts from wiki db. Can anyone provide me with a concrete example to convert a context to text?

Best regards
sayef

**Comment by Raldir** [comment]
Hello,

Sorry for the delayed reply. You can call this function from a `wiki_page` object, using as the argument the element id:
https://github.com/Raldir/FEVEROUS/blob/113a2082ebabb56abf6b008aad5286428506f1c4/src/feverous/utils/wiki_page.py#L181

Hope this answers your question, let me know if there is anything else!
