### ISSUE TITLE
Querying DB with texts with special symbols does not return results.

### ISSUE THREAD

**Issue by narayanacharya6** [Raldir/FEVEROUS#3]
I've noticed search queries with umlauts and other symbols also return nothing from the database while in fact there is a result in there.

For example: If I try to search for `Didier Lourenço` using `db.get_doc_json()` it returns nothing. But when I try to search the database directly using `SELECT * FROM wiki WHERE id = 'Didier Lourenço';` it does return the correct result from the database.

The line under `src/database/feverous_db.py` to "normalize" the `doc_id` is commented out.

https://github.com/Raldir/FEVEROUS/blob/main/src/database/feverous_db.py#L47-L57

Using the "normalized" query seems to work. Any reason why this was commented out?

**Comment by narayanacharya6** [comment]
Also, here is a list of queries that do not work even after using the "normalized" text. Maybe we need to handle these separately (or maybe just ignore them).

```
['Artim Šakiri', 'Kazys Škirpa', 'Škoda Auto Museum', 'ʻIʻiwi', 'Kristian Wåhlin', 'Kåre Harila', 'Špania Dolina', 'Themistokli Gërmenji', 'NK GOŠK Gabela', 'Škoda Fabia', 'Baháʼí Faith in Cameroon', 'Švitrigaila', 'Håkon Opdal', 'Pål Varhaug', 'Baháʼí Faith by country', 'İpek Soylu', 'Šance Dam', 'Šardinje', 'Kahoʻolawe', 'Maija Tīruma', 'Šentilj v Slovenskih Goricah', 'Baháʼí Faith', 'Roman Štrba', 'Vladimir Štimac', 'Baháʼí News', 'Tʼazur Company', 'Kwakwakaʼwakw']
```

**Comment by narayanacharya6** [comment]
Whoops, just saw the only other issue on the repo that addresses this. Closing.

**Comment by Raldir** [comment]
Sorry for this issue. The full training set (and then also the dev set) to be released very soon will have this fixed.
