### ISSUE TITLE
IndexError in predict_cells_from_table.py

### ISSUE THREAD

**Issue by rayhuang11** [Raldir/FEVEROUS#30]
@Raldir, thanks again for your help. I managed to run the baseline code successfully up to the point where

```
python3 -m feverous.baseline.retriever.predict_cells_from_table --input_path ../data/dev.combined.not_precomputed.p5.s5.t3.jsonl --wiki_path ../data/feverous_wikiv1.db --config_path feverous/baseline/retriever/config_roberta.json
```

where I get an `IndexError` in the `extract_tables_from_cells` function on this line `logger.info("Sample entry: {}".format(all_input[0]))`.

I tried debugging and tracing upstream, and this is some of the output I got:

- The `all_input` variable right before the error message is empty.
- In the loop in `extra_tables_from_cells` I added `if not tabs: logger.warning(f"No tabs returned for annotation {i} with id {anno.get_id()}.")` and saw no tabs are being returned.

I then went into the `convert_evidence_into_tables` function saw that:

- I added these two print statements before the loop to check annotation ID and confirm tables are found, to which I got the following output: `Processing annotation: 7890. Total tables to process: 0`
- I also tried printing `output_tables, output_tables_ids` at the end of the function and got empty lists.

To my knowledge, there doesn't seem to be an any errors upstream, as all the inputs look good. Any advice would be appreciated, thanks!

**Comment by rayhuang11** [comment]
@Raldir hope you had a good weekend! I did some further troubleshooting and this is what I found. This time I tried running the baseline code with the instructions for the readme in the directory root. I'm still getting `DOC2IDX: None`. Here is the traceback:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/rayhuang/anaconda3/envs/feverous/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/rayhuang/Documents/Blueprint_Labs/FEVEROUS/src/feverous/baseline/drqascripts/build_tfidf.py", line 80, in count
    if doc_id in DOC2IDX:
TypeError: argument of type 'NoneType' is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/baseline.py", line 56, in <module> build_tfidf(db_path=args.tf_idf_db_path, out_dir=args.tf_idf_index_path)
  File "/Users/rayhuang/Documents/Blueprint_Labs/FEVEROUS/src/feverous/baseline/retriever/build_tfidf.py", line 26, in build_tfidf
count_matrix, doc_dict = get_count_matrix("sqlite", {"db_path": db_path}, ngram, hash_size, tokenizer, num_workers)
  File "/Users/rayhuang/Documents/Blueprint_Labs/FEVEROUS/src/feverous/baseline/drqascripts/build_tfidf.py", line 113, in get_count_matrix
    for b_row, b_col, b_data in workers.imap_unordered(_count, batch):
  File "/Users/rayhuang/anaconda3/envs/feverous/lib/python3.8/multiprocessing/pool.py", line 868, in next
DOC2IDX: None
    raise value
TypeError: argument of type 'NoneType' is not iterable
```

I'll keep troubleshooting and post anything that comes up, thanks~!

**Comment by Raldir** [comment]
Hey @rayhuang11, I am sorry for not getting back to you earlier, this weekend was very busy.

Thanks for the update! This is odd. Can you check that (i) the path to the FEVEROUS db are specified correctly (i.e. https://github.com/Raldir/FEVEROUS/blob/72b5bce684a169f57633cca0d186ab1de3e17757/examples/baseline.py#L20C6-L20C6), (ii) that the tf-idf db constructed in the first step of the baseline looks sound (e.g. check size of the DB, run a simple query on it such the function `get_doc_ids` as shown in: (https://github.com/Raldir/FEVEROUS/blob/72b5bce684a169f57633cca0d186ab1de3e17757/src/feverous/baseline/drqa/retriever/doc_db.py#L38).

**Comment by rayhuang11** [comment]
@Raldir no worries, thanks for the help. To respond to your suggestions

i) `db_path` is specified as `"data/feverous-wiki-pages.db`. 

ii) the path is specified correctly (to `data/feverous-wiki-docs.db`)

For i) and ii), I printed out the value of the arguments and it seems correct. 

iii) The pages.db file is about 50 gb, while the docs is about > 20 gb. I ran the `DocDB` `get_doc_ids` method on the pages doc, and got 
```
The number of documents in the database is: 5421406
Some document ids are: ['', '! (Cláudia Pascoal album)', '! (The Dismemberment Plan album)', '! (The Song Formerly Known As)', '! (Trippie Redd album)']
```

Thanks for the help!

**Comment by rayhuang11** [comment]
@Raldir here is some additional information that might help. It seems like the issue is most likely associated with the multiprocessing or count function in `drqascripts/build_tfidf.py`. The error is specifically originating from this line:

https://github.com/Raldir/FEVEROUS/blob/d1887a2ef7f707aac09b253d2c9e26f0d1408723/src/feverous/baseline/drqascripts/build_tfidf.py#L107

I printed out all the inputs to the `get_count_matrix` function and got:

```
db:  sqlite
db_opts:  {'db_path': '../data/feverous-wiki-docs.db'}
ngram:  2
hash_size:  16777216
tokenizer:  simple
num_workers:  None
```

Within the `get_matrix_count` function, I also printed `DOC2IDX` and `batches, both of which seem to be filled correctly. Perhaps its an issue with `workers`?

Thank you!

**Comment by Raldir** [comment]
Hey @rayhuang11. Thanks for the additional info. Can you confirm that the error message you receive is still this one?

> multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/rayhuang/anaconda3/envs/feverous/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/rayhuang/Documents/Blueprint_Labs/FEVEROUS/src/feverous/baseline/drqascripts/build_tfidf.py", line 80, in count
    if doc_id in DOC2IDX:
TypeError: argument of type 'NoneType' is not iterable
"""
Where is `if doc_id in DOC2IDX` located? It is not in the original source code I believe. Maybe it is an artifact from your debugging?

Specifying `num_workers=none` automatically uses `os.cpu_count()`, see [here] (https://docs.python.org/3/library/multiprocessing.html). However, the problem does appear to stem from the count function. Can you provide more detailed info where exactly the values start to be off (i.e. check that `tokens`, `ngram`, etc. all look fine)?

**Comment by rayhuang11** [comment]
@Raldir yes, that is still the correct error message. The `if` statement is just leftover from debugging. I get almost exactly the same issue when I run it without the statement:

```
"""
Traceback (most recent call last):
  File "/Users/rayhuang/anaconda3/envs/feverous/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/rayhuang/Documents/Blueprint_Labs/FEVEROUS/src/feverous/baseline/drqascripts/build_tfidf.py", line 79, in count
    col.extend([DOC2IDX[doc_id]] * len(counts))
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "feverous/baseline/retriever/build_tfidf.py", line 74, in <module>
    build_tfidf(args.db_path, args.out_dir, args.ngram, args.hash_size, args.tokenizer, args.num_workers)
  File "feverous/baseline/retriever/build_tfidf.py", line 26, in build_tfidf
    count_matrix, doc_dict = get_count_matrix("sqlite", {"db_path": db_path}, ngram, hash_size, tokenizer, num_workers)
  File "/Users/rayhuang/Documents/Blueprint_Labs/FEVEROUS/src/feverous/baseline/drqascripts/build_tfidf.py", line 136, in get_count_matrix
    for b_row, b_col, b_data in workers.imap_unordered(_count, batch):
  File "/Users/rayhuang/anaconda3/envs/feverous/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
TypeError: 'NoneType' object is not subscriptable
```

I printed out the inputs to the `get_matrix_function` right after it was called and got this (is this what you are referring to):
```
db:  sqlite
db_opts:  {'db_path': '../data/feverous-wiki-docs.db'}
ngram:  2
hash_size:  16777216
tokenizer:  simple
num_workers:  None
```

**Comment by Raldir** [comment]
@rayhuang11 How are you calling the function `build_tfidf` right now? If you call it via `examples/baseline.py` then the path should be `data/feverous-wiki-docs.db`. So to confirm: when checking DOC2IDX in `get_count_matrix` after line 93 and before line 104 it works fine, but once it is being used in function `count` DOC2IDX is None? I am not sure how this is possible since DOC2IDX is assigned only in line 93 and not after that again. You could try checking if setting `num_workers` changes anything but I doubt that. Alternatively, if you remove the multiprocessing will it then work (just call count for each doc_id naively)? I am not sure what else might cause this issue since the code is running without problems on my end.

**Comment by rayhuang11** [comment]
@Raldir it's helpful to know the code is working on your end without problems. 

To clarify, DOC2IDX is working fine prior to this line: 

https://github.com/Raldir/FEVEROUS/blob/d1887a2ef7f707aac09b253d2c9e26f0d1408723/src/feverous/baseline/drqascripts/build_tfidf.py#L78

I'll continue if that troubleshoot, and try removing multiprocessing. Thanks.

**Comment by Raldir** [comment]
Hey @rayhuang11. Are you using Windows by any chance? I just went to the DrQA repository (which this part of the code is taken from) and found this related issue: https://github.com/facebookresearch/DrQA/issues/34

I was not ware that Windows handles global variables differently but there you go. Sorry about that. So either you can run the code with a single worker for now, change your operating system, or once I have a bit more time at hand I can modify the code to do without global variables (bad style anyway).

**Comment by rayhuang11** [comment]
Hi @Raldir, thanks for the suggestion. I'm using Mac, but it seems like it was an issue with the way the different cores were getting `DOC2IDX` var. I resolved it by modifying the `init` function, and it ran with multiprocessing. It's very strange that it worked on some but not all machines. I submit my edits later in a PR so you can see for yourself.

Unfortunately, another issue has cropped up which has me a bit stumped. When running baseline, in the `cell_retrieval` function, I get the following error message:

```
Traceback (most recent call last):
  File "examples/baseline.py", line 91, in <module>
    cell_retrieval(
  File "/Users/rayhuang/Documents/Blueprint_Labs/FEVEROUS/src/feverous/baseline/retriever/predict_cells_from_table.py", line 354, in cell_retrieval
    extract_cells_from_tables(annotations, input_path, wiki_path, trivial_baseline, config)
  File "/Users/rayhuang/Documents/Blueprint_Labs/FEVEROUS/src/feverous/baseline/retriever/predict_cells_from_table.py", line 255, in extract_cells_from_tables
    logger.info("Sample entry: {}".f
```

In this case, the 4 lists in `extract_cells_from_tables` are empty. Looking deeper into `convert_evidence_into_tables`, I see that the list comprehension for `predicted_sentences` and `predicted_tables` is returning empty lists as well.

When I looked at the data (`dev.combined.not_precomputed.p5.s5.t3.jsonl`), I see that the `predicted_evidence` is empty, i.e. `annotation.predicted_evidence` is empty. 

- `dev.sentences` and `dev.tables` also have empty predicted lists. 
- `dev.pages` looks fine, as the `predicted_pages` are populated.

Any advice is greatly appreciated, thanks!

**Comment by rayhuang11** [comment]
I believe I found a solution to the above issue. The sentence and table retrieval parts was incorrectly calling the `DocDB` class when it should have been calling the `FeverousDB`, since both functions try to use `get_doc_json` which only exist in `FeverousDB`.

**Comment by Raldir** [comment]
Hi @rayhuang11, thanks! Huh, sounds like an issue caused by the lastest refactoring. If you could open a PR that would be great. I am sorry for being slow with responding, this week and the next will be busy but I will have a proper look after that. Feel free to open a PR in the meantime, much appreciated.

**Comment by rayhuang11** [comment]
No worries at all, thank you for all your help!

**Comment by rayhuang11** [comment]
@Raldir thank you for your help! I'm very grateful. I've opened a PR, #31. Closing this issue for now.
