### ISSUE TITLE
Baseline Issues

### ISSUE THREAD

**Issue by varadhbhatnagar** [Raldir/FEVEROUS#5]
There seem to be many path issues in the baseline code. Some issues that I could find:

1. `common` directory is missing.
2.  Some methods like `get_contents_sentence()` in `src/baseline/retriever/build_db.py` seem to misplaced.

Please check if the baseline code scripts can be run under the directory structure given in this repository.

**Comment by Raldir** [comment]
Code has been updated, dependencies are fixed. Feel free to open this issue if any issues in running the baseline are encountered.
