### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by bruel-gabrielsson** [Raldir/FEVEROUS#6]
HI! Can I get your email or can you email me at rgabriel@stanford.edu?

**Comment by Raldir** [comment]
Hi Bruel,

feel free to reach out by e-mail `rmya2@cam.ac.uk` or on the [Fever Workshop slack channel](https://join.slack.com/t/feverworkshop/shared_invite/zt-4v1hjl8w-Uf4yg~diftuGvj2fvw7PDA).
