### ISSUE TITLE
Mismatching document IDs in training data and database

### ISSUE THREAD

**Issue by Martin36** [Raldir/FEVEROUS#7]
It seems that some documents have different IDs in the training data and in the database. For example the train data example nr 52, with the claim and evidence as follows: 
```
'claim': 'Participating teams in the 2012–13 Macedonian First Football League '
          'included club Bregalnica, managed by Dobrinko Ilievski, and club '
          'Shkëndija, managed by Artim Shakiri, a retired football midfielder '
          'from North Macedonia.',
 'evidence': [{'content': ['2012–13 Macedonian First Football '
                           'League_cell_1_1_0',
                           '2012–13 Macedonian First Football '
                           'League_cell_1_1_1',
                           '2012–13 Macedonian First Football '
                           'League_cell_1_8_0',
                           '2012–13 Macedonian First Football '
                           'League_cell_1_8_1',
                           'Artim Šakiri_sentence_0'],
```
Here one part of the evidence is from the document `Artim Šakiri`. But trying to get a document with this ID from the database returns `None`. By looking through the list of IDs in the database I found that the closest one to `Artim Šakiri` is `Artim Å akiri`.

**Comment by Raldir** [comment]
Hi Martin,

This has been an issue with the old version (batch 1) of the training file. To fix this for the old training/dev file you can call `get_wikipage_by_id("Artim Šakiri", db)` from `wiki_page.py`.
However, I would strongly recommend downloading the final training and development data as the size of the training data is substantially larger as well now (over 70k samples): https://fever.ai/dataset/feverous.html
In this version, the annotation data has already processed to cover these cases so this error should not occur anymore.

We will add a Change-log to be clearer on this!
